[package]
name = "shitspeak-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-lc-rs = "1.15.2"
bytes = "1.11.0"
chrono = { version = "0.4.41", features = ["serde"] }
cidr = "0.3.2"
config = "0.15.19"
notify = { version = "7", default-features = false, features = ["macos_kqueue"] }
enumflags2 = { version = "0.7.12", features = ["serde"] }
hex = "0.4.3"
maxminddb = { version = "0.26.0", features = ["mmap", "simdutf8"] }
num_enum = "0.7.5"
paste = "1.0.15"
ppp = "2.3.0"
prost = "0.13.5"
prost-types = "0.13.5"
rustls = "0.23.35"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["stream"] }
thiserror = "2.0.17"
tokio = { version = "1.45.0", features = ["full"] }
tokio-rustls = "0.26.4"
tracing = "0.1"
tracing-appender = { version = "0.2.4", features = ["parking_lot"] }
tracing-subscriber = { version = "0.3.22", features = ["parking_lot", "serde", "env-filter"] }

# local proc-macro to derive message helpers
message_macro = { path = "src/messages/macros" }
os_info = "3.14.0"
async-trait = "0.1.89"
rusqlite = { version = "0.31", features = ["bundled"] }
parking_lot = { version = "0.12.5", features = ["arc_lock", "hardware-lock-elision", "owning_ref", "send_guard", "serde"] }
scc = "2.0"

[build-dependencies]
chrono = "0.4.41"
prost-build = "0.13.5"

[dev-dependencies]
rcgen = "0.13"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "acl"
harness = false
