[package]
name = "shitspeak-runtime-config"
version.workspace = true
edition.workspace = true

[dependencies]
config = { workspace = true }
serde = { workspace = true }
shitspeak-auth = { workspace = true }
shitspeak-core = { workspace = true }
shitspeak-s2s = { workspace = true }
shitspeak-s2s-transport = { workspace = true }

[dev-dependencies]
rcgen = { workspace = true }
tempfile = { workspace = true }
