[package]
name = "shitspeak-web"
version.workspace = true
edition.workspace = true

[dependencies]
aws-lc-rs = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
hang = { workspace = true, optional = true }
moq-native = { workspace = true, optional = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shitspeak-auth = { workspace = true }
shitspeak-runtime = { workspace = true }
shitspeak-runtime-config = { workspace = true }
shitspeak-state = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tracing = { workspace = true }
webrtc = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }
rcgen = { workspace = true }
rustls = { workspace = true }
tempfile = { workspace = true }

[features]
default = []
moq = ["dep:hang", "dep:moq-native"]
